import type { Metadata } from "next";
import { FadeIn } from "@/components/motion/FadeIn";
import { BLOCK_EXPLORER, CONTRACTS, IS_MAINNET } from "@/lib/contracts";

export const metadata: Metadata = {
  title: "Whitepaper — Project POH",
  description:
    "The full Project POH whitepaper: the Voyager Block Model, dual-work mining, RTG decay, BOINC integration, and the Voyager Chase Fund.",
  openGraph: {
    title: "Whitepaper — Project POH",
    description:
      "The full Project POH whitepaper: the Voyager Block Model, dual-work mining, RTG decay, BOINC integration, and the Voyager Chase Fund.",
  },
};

export default function WhitepaperPage() {
  return (
    <div className="bg-background py-20 sm:py-28">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        {/* ── Header ── */}
        <FadeIn>
          <header className="mb-16 text-center">
            <h1 className="text-4xl font-bold tracking-tight text-accent-light sm:text-5xl">
              Project POH Whitepaper
            </h1>
            <p className="mt-4 text-lg text-foreground/50">Version 3.0 — Voyager Block Model</p>
          </header>
        </FadeIn>

        {/* ── Mission ── */}
        <Section id="mission" title="Mission">
          <blockquote className="border-l-4 border-voyager-gold pl-6 text-xl font-medium italic leading-relaxed text-foreground/90">
            Change the trajectory of humankind by creating the most trusted
            charity crypto ecosystem on the planet.
          </blockquote>
        </Section>

        {/* ── The Voyager Block Model ── */}
        <Section id="voyager-block-model" title="The Voyager Block Model">
          <p>
            Project POH introduces a revolutionary mining model tied to{" "}
            <strong className="text-voyager-gold">Voyager&nbsp;1</strong>, humanity&rsquo;s
            most distant spacecraft. Unlike traditional blockchain mining, POH blocks are
            generated by Voyager&rsquo;s actual distance from Earth.
          </p>
          <ul className="mt-6 list-disc space-y-3 pl-6 marker:text-accent-light">
            <li>
              <strong>24.526 billion POH tokens</strong> were minted at launch,
              representing Voyager&nbsp;1&rsquo;s distance in kilometres (24.526B km)
              at the project&rsquo;s genesis.
            </li>
            <li>
              <strong>Every 1,000 km Voyager travels beyond 24.526B km = 1 new block.</strong>{" "}
              At Voyager&rsquo;s current velocity of 16.88 km/s, this produces approximately{" "}
              <strong>~1,459 new blocks per day</strong>.
            </li>
            <li>
              <strong>12.263 billion POH</strong> (50% of supply) sits in the POHRewards
              contract, serving as the block reward pool.
            </li>
            <li>
              <strong>Miners solve BOTH compute tasks AND a SHA-256 block equation</strong>{" "}
              to earn rewards &mdash; dual-work mining that combines social good with
              cryptographic proof-of-work.
            </li>
            <li>
              <strong>Block rewards follow RTG decay</strong> (like Voyager&rsquo;s
              radioisotope thermoelectric generators), reducing by 5% annually. This
              creates a smooth, predictable emission curve.
            </li>
            <li>
              <strong>When Voyager is decommissioned (~2030-2036), blocks stop forever.</strong>{" "}
              Any POH remaining in the rewards pool becomes permanently locked, creating
              ultimate scarcity.
            </li>
            <li>
              <strong>Distance formula:</strong>{" "}
              <code className="rounded bg-surface-light px-2 py-1 text-sm font-mono">
                distance(t) = 25,316,070,000 + (1,458,648 × daysSinceEpoch)
              </code>
              , where epoch is January 1, 2026.
            </li>
          </ul>
        </Section>

        {/* ── Dual-Work Mining ── */}
        <Section id="dual-work-mining" title="Dual-Work Mining">
          <p>
            POH mining runs two parallel Web Workers in your browser, ensuring both
            computational science and cryptographic security.
          </p>

          <h3 className="mt-6 text-lg font-semibold text-accent-light">
            Science Worker
          </h3>
          <ul className="mt-3 list-disc space-y-2 pl-6 marker:text-accent-light">
            <li>
              <strong>Folding@home protein folding</strong> &mdash; contributes to
              disease research (Alzheimer&rsquo;s, cancer, COVID-19)
            </li>
            <li>
              <strong>In-browser compute tasks:</strong> protein structure prediction,
              climate modeling, signal processing, drug screening
            </li>
            <li>
              <strong>BOINC projects:</strong> Rosetta@home, Einstein@Home,
              Climateprediction.net, World Community Grid (see BOINC Integration below)
            </li>
          </ul>

          <h3 className="mt-6 text-lg font-semibold text-accent-light">
            Block Equation Worker
          </h3>
          <ul className="mt-3 list-disc space-y-2 pl-6 marker:text-accent-light">
            <li>
              <strong>SHA-256 proof-of-work</strong> using WASM (hash-wasm library)
              for near-native performance
            </li>
            <li>
              <strong>Adaptive difficulty:</strong> 6-7 leading hex zeros, targeting
              5-10 minute solve time on a modern smartphone
            </li>
            <li>
              <strong>Self-throttling:</strong> block worker yields CPU time to science
              tasks, ensuring science gets priority
            </li>
          </ul>

          <h3 className="mt-6 text-lg font-semibold text-accent-light">
            Mining Requirements
          </h3>
          <p className="mt-3">
            Both conditions must be met to mine a block:
          </p>
          <ol className="mt-3 list-decimal space-y-2 pl-6 marker:text-accent-light">
            <li>
              <strong>N verified compute tasks completed</strong> &mdash; starts at 20
              tasks/block in early network, scales to 200 tasks/block as adoption grows
            </li>
            <li>
              <strong>Block equation solved</strong> &mdash; valid SHA-256 hash meeting
              difficulty target
            </li>
          </ol>

          <h3 className="mt-6 text-lg font-semibold text-accent-light">
            Block Reward Split
          </h3>
          <div className="mt-3 overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-surface-light">
                  <th className="py-3 pr-4 font-semibold text-accent-light">
                    Recipient
                  </th>
                  <th className="py-3 font-semibold text-accent-light">
                    Share
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-light text-foreground/80">
                <Row label="Equation Solver" value="60%" />
                <Row label="Task Contributors" value="30%" />
                <Row label="F@H / BOINC Bonus" value="10%" />
              </tbody>
            </table>
          </div>
        </Section>

        {/* ── RTG Decay Reward Schedule ── */}
        <Section id="rtg-decay" title="RTG Decay Reward Schedule">
          <p>
            Block rewards decay at 5% annually, mirroring the degradation of
            Voyager&rsquo;s radioisotope thermoelectric generators. This creates a
            smooth, predictable emission curve with intentional scarcity.
          </p>
          <div className="mt-6 overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-surface-light">
                  <th className="py-3 pr-4 font-semibold text-accent-light">Year</th>
                  <th className="py-3 pr-4 font-semibold text-accent-light">
                    Annual Emission
                  </th>
                  <th className="py-3 pr-4 font-semibold text-accent-light">
                    Block Reward
                  </th>
                  <th className="py-3 pr-4 font-semibold text-accent-light">
                    Cumulative
                  </th>
                  <th className="py-3 font-semibold text-accent-light">
                    Remaining
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-light text-foreground/80">
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">1</td>
                  <td className="py-3 pr-4 font-mono text-sm">~536M POH</td>
                  <td className="py-3 pr-4 font-mono text-sm">~1,009 POH</td>
                  <td className="py-3 pr-4 font-mono text-sm">536M</td>
                  <td className="py-3 font-mono text-sm">11.73B</td>
                </tr>
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">5</td>
                  <td className="py-3 pr-4 font-mono text-sm">~434M POH</td>
                  <td className="py-3 pr-4 font-mono text-sm">~817 POH</td>
                  <td className="py-3 pr-4 font-mono text-sm">2.43B</td>
                  <td className="py-3 font-mono text-sm">9.83B</td>
                </tr>
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">10</td>
                  <td className="py-3 pr-4 font-mono text-sm">~338M POH</td>
                  <td className="py-3 pr-4 font-mono text-sm">~636 POH</td>
                  <td className="py-3 pr-4 font-mono text-sm">4.71B</td>
                  <td className="py-3 font-mono text-sm">7.55B</td>
                </tr>
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">20</td>
                  <td className="py-3 pr-4 font-mono text-sm">~202M POH</td>
                  <td className="py-3 pr-4 font-mono text-sm">~381 POH</td>
                  <td className="py-3 pr-4 font-mono text-sm">7.85B</td>
                  <td className="py-3 font-mono text-sm">4.41B</td>
                </tr>
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">∞</td>
                  <td className="py-3 pr-4 font-mono text-sm">&mdash;</td>
                  <td className="py-3 pr-4 font-mono text-sm">&mdash;</td>
                  <td className="py-3 pr-4 font-mono text-sm">10.72B</td>
                  <td className="py-3 font-mono text-sm">1.54B</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="mt-4">
            <strong>Key insight:</strong> RTG decay mathematically converges such that{" "}
            <strong>only 10.72B POH can ever be distributed</strong> from the rewards pool.
            The remaining <strong className="text-voyager-gold">1.54B POH becomes permanently
            unreachable</strong> &mdash; locked in the contract forever. This is not a bug;
            it&rsquo;s intentional scarcity and becomes the seed capital for the{" "}
            <strong>Voyager Chase Fund</strong>.
          </p>
        </Section>

        {/* ── Supply Allocation ── */}
        <Section id="supply-allocation" title="Supply Allocation">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-surface-light">
                  <th className="py-3 pr-4 font-semibold text-accent-light">
                    Allocation
                  </th>
                  <th className="py-3 pr-4 font-semibold text-accent-light">
                    Share
                  </th>
                  <th className="py-3 pr-4 font-semibold text-accent-light">
                    Tokens
                  </th>
                  <th className="py-3 font-semibold text-accent-light">
                    Notes
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-light text-foreground/80">
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">
                    Community Rewards
                  </td>
                  <td className="py-3 pr-4">50%</td>
                  <td className="py-3 pr-4 font-mono text-sm">12.263B</td>
                  <td className="py-3">Block mining rewards, RTG decay</td>
                </tr>
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">
                    Charity Treasury
                  </td>
                  <td className="py-3 pr-4">20%</td>
                  <td className="py-3 pr-4 font-mono text-sm">4.905B</td>
                  <td className="py-3">
                    Governed by founder then DAO
                  </td>
                </tr>
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">
                    Liquidity Pool
                  </td>
                  <td className="py-3 pr-4">15%</td>
                  <td className="py-3 pr-4 font-mono text-sm">3.679B</td>
                  <td className="py-3">Uniswap on Base</td>
                </tr>
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">
                    Founder
                  </td>
                  <td className="py-3 pr-4">10%</td>
                  <td className="py-3 pr-4 font-mono text-sm">2.453B</td>
                  <td className="py-3">
                    4-year vesting, 6-month cliff
                  </td>
                </tr>
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">
                    Airdrop / Marketing
                  </td>
                  <td className="py-3 pr-4">5%</td>
                  <td className="py-3 pr-4 font-mono text-sm">1.226B</td>
                  <td className="py-3">&mdash;</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Section>

        {/* ── BOINC Integration ── */}
        <Section id="boinc-integration" title="BOINC Integration">
          <p>
            POH miners can optionally link their{" "}
            <strong>BOINC Cross-Project ID (CPID)</strong> to earn bonus rewards for
            verified scientific computing contributions.
          </p>
          <ul className="mt-6 list-disc space-y-3 pl-6 marker:text-accent-light">
            <li>
              <strong>Supported projects:</strong> Rosetta@home (protein structure
              prediction), Einstein@Home (gravitational wave detection),
              Climateprediction.net (climate modeling), World Community Grid
              (humanitarian research).
            </li>
            <li>
              <strong>NOT SETI@home</strong> &mdash; SETI has been in hibernation
              since March 2020.
            </li>
            <li>
              <strong>10 POH bonus points per BOINC credit</strong> &mdash; verified
              via project APIs with 24-hour caching to reduce load.
            </li>
            <li>
              Your CPID is a 32-character hexadecimal identifier visible in your BOINC
              client. Simply paste it into your POH mining dashboard to link accounts.
            </li>
          </ul>
        </Section>

        {/* ── Fee Rationale ── */}
        <Section id="fee-rationale" title="Fee Rationale">
          <ul className="list-disc space-y-3 pl-6 marker:text-accent-light">
            <li>
              <strong>Low buy fee (1%)</strong> encourages entry and lowers the
              barrier for new holders who want to support charitable causes.
            </li>
            <li>
              <strong>Higher sell fee (3%)</strong> discourages short-term
              dumping while channelling a larger share of proceeds to the charity
              treasury.
            </li>
            <li>
              <strong>Burn on sells (1%)</strong> permanently removes tokens from
              circulation, making POH deflationary over time and rewarding
              long-term holders.
            </li>
            <li>
              <strong>Transfer fee (0.5%)</strong> ensures that even
              peer-to-peer transfers contribute to the charity mission, closing a
              common fee-avoidance loophole.
            </li>
          </ul>
        </Section>

        {/* ── The Decommission Event ── */}
        <Section id="decommission-event" title="The Decommission Event">
          <p>
            Voyager&nbsp;1 is powered by three radioisotope thermoelectric generators
            (RTGs) that decay at ~4 watts per year. NASA estimates the spacecraft will
            lose all power and go silent sometime between{" "}
            <strong className="text-voyager-gold">2030 and 2036</strong>.
          </p>
          <p className="mt-4">
            When Voyager&nbsp;1 transmits its final signal:
          </p>
          <ul className="mt-4 list-disc space-y-3 pl-6 marker:text-accent-light">
            <li>
              <strong>Block generation stops forever.</strong> No new blocks will be
              mined, no matter how much compute is contributed.
            </li>
            <li>
              <strong>Remaining POH in the rewards pool is permanently locked.</strong>{" "}
              The contract becomes read-only. That POH can never be distributed.
            </li>
            <li>
              The website displays a memorial:{" "}
              <span className="italic text-foreground/60">
                "Voyager 1 has gone silent. Final block: #XXXXX. Distance: XX.XXB km."
              </span>
            </li>
            <li>
              Like lost Bitcoin in Satoshi&rsquo;s wallet, this creates{" "}
              <strong>permanent scarcity</strong> &mdash; a fixed supply that can never
              expand again.
            </li>
          </ul>
          <p className="mt-4 text-lg font-semibold text-accent-light">
            But POH doesn&rsquo;t end when Voyager goes silent. It begins.
          </p>
        </Section>

        {/* ── The Voyager Chase Fund ── */}
        <Section id="voyager-chase-fund" title="The Voyager Chase Fund">
          <p className="text-lg font-semibold text-voyager-gold">
            This is the crown jewel of Project POH.
          </p>
          <p className="mt-4">
            When Voyager&nbsp;1 is decommissioned, the POH DAO votes on{" "}
            <strong>&ldquo;The Transition&rdquo;</strong> &mdash; a one-time governance
            proposal to convert the remaining rewards pool into the{" "}
            <strong className="text-voyager-gold">Voyager Chase Fund</strong>.
          </p>

          <h3 className="mt-6 text-lg font-semibold text-accent-light">
            How It Works
          </h3>
          <ul className="mt-3 list-disc space-y-3 pl-6 marker:text-accent-light">
            <li>
              The fund is governed by the existing{" "}
              <strong>POHGovernor and POHTimelock contracts</strong> (already deployed
              on Base mainnet).
            </li>
            <li>
              Funds are distributed via DAO vote to{" "}
              <strong>vetted interstellar research organisations</strong>: The Planetary
              Society, Breakthrough Initiatives, university astrophysics labs, and space
              agencies.
            </li>
            <li>
              The community votes on which projects receive grants &mdash; proposals
              must demonstrate credible research into deep-space propulsion, autonomous
              probes, or interstellar navigation.
            </li>
            <li>
              The mathematically unreachable{" "}
              <strong className="text-voyager-gold">1.54B POH</strong> acts as a seed
              fund, accumulating value from day one of the token&rsquo;s existence.
            </li>
            <li>
              <strong>The ultimate goal:</strong> fund an AI-guided autonomous probe to
              intercept and recover Voyager&nbsp;1, humanity&rsquo;s farthest artifact.
            </li>
          </ul>

          <h3 className="mt-6 text-lg font-semibold text-accent-light">
            Real-World Context
          </h3>
          <p className="mt-3">
            This is ambitious but not science fiction:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-6 marker:text-accent-light">
            <li>
              <strong>Parker Solar Probe</strong> reaches 191 km/s using gravity assists.
            </li>
            <li>
              <strong>Breakthrough Starshot</strong> targets 0.2c (20% speed of light)
              using laser-sail propulsion.
            </li>
            <li>
              Voyager&nbsp;1 is currently 24.5+ billion km away, moving at 16.88 km/s.
              An intercept mission is difficult but feasible with 21st-century technology.
            </li>
          </ul>

          <p className="mt-6 text-lg font-semibold text-accent-light">
            POH doesn&rsquo;t end when Voyager goes silent. It begins.
          </p>
        </Section>

        {/* ── Voyager 2 Fork ── */}
        <Section id="voyager-2-fork" title="Voyager 2 Fork">
          <p>
            When Voyager&nbsp;1 is decommissioned, the POH community will have the
            option to fork the protocol to a new chain tied to{" "}
            <strong>Voyager&nbsp;2&rsquo;s distance</strong>.
          </p>
          <ul className="mt-6 list-disc space-y-3 pl-6 marker:text-accent-light">
            <li>
              <strong>New expanding supply</strong> based on Voyager&nbsp;2&rsquo;s
              ongoing journey.
            </li>
            <li>
              <strong>Same dual-work mining model</strong> &mdash; science tasks + block
              equation.
            </li>
            <li>
              <strong>Smooth transition for miners</strong> &mdash; existing V1 miners
              can migrate to V2 without retooling infrastructure.
            </li>
            <li>
              This is a <strong>10-20 year horizon</strong>. Voyager&nbsp;2 will outlive
              Voyager&nbsp;1 by several years. The fork is not built today but planned
              as a future governance decision.
            </li>
          </ul>
        </Section>

        {/* ── Security ── */}
        <Section id="security" title="Security">
          <ul className="list-disc space-y-3 pl-6 marker:text-accent-light">
            <li>
              Built on{" "}
              <strong>OpenZeppelin v5 battle-tested contracts</strong> &mdash;
              the industry gold standard for Solidity security.
            </li>
            <li>
              <strong>Emergency pause capability</strong> is retained during the
              early phases under a progressive decentralisation plan, ensuring
              the team can react to critical vulnerabilities.
            </li>
            <li>
              All contract source code is{" "}
              <strong>open source and verified on Basescan</strong> so anyone can
              audit the on-chain logic.{" "}
              <a
                href="https://github.com/chatde/poh-coin"
                target="_blank"
                rel="noopener noreferrer"
                className="text-accent-light underline underline-offset-2 hover:text-accent"
              >
                View on GitHub
              </a>
              .
            </li>
            <li>
              <strong>Slither static analysis passed</strong> (by Trail of
              Bits) &mdash; automated vulnerability scanning confirms no
              critical or high-severity findings across all 7 contracts.
            </li>
            <li>
              <strong>Mythril symbolic execution passed</strong> (by
              ConsenSys) &mdash; zero issues detected. Checks for reentrancy,
              integer overflow, access control, and more.
            </li>
            <li>
              All 7 contracts are{" "}
              <strong>deployed and verified on Base mainnet</strong>. Source
              code is publicly readable on Basescan.
            </li>
          </ul>
        </Section>

        {/* ── Governance ── */}
        <Section id="governance" title="Charity Treasury Governance">
          <p>
            The 20% charity treasury (4.905B POH) is the backbone of the
            project&rsquo;s mission. Governance is powered by an{" "}
            <strong>OpenZeppelin Governor</strong> contract with a{" "}
            <strong>48-hour TimelockController</strong>, enabling fully
            on-chain token-weighted voting. The system follows a
            progressive decentralisation model:
          </p>
          <ul className="mt-6 list-disc space-y-3 pl-6 marker:text-accent-light">
            <li>
              <strong>Phase 1 &mdash; Founder-Governed (current):</strong>{" "}
              The founder proposes charity distributions through the
              POHCharity contract. Every proposal has a{" "}
              <strong>24-hour timelock</strong> before execution, giving the
              community time to review and object. All proposals and
              executions are on-chain and publicly verifiable.
            </li>
            <li>
              <strong>Phase 2 &mdash; Community Advisory:</strong> As the
              community grows, a council of elected token holders will
              review and approve proposals before the founder executes them.
              Veto power transitions to the community.
            </li>
            <li>
              <strong>Phase 3 &mdash; Full DAO:</strong> Governance
              transitions to a token-weighted DAO where POH holders vote
              directly on charity distributions, recipient selection, and
              treasury strategy. The founder becomes one vote among many.
            </li>
          </ul>
          <p className="mt-4">
            This graduated approach ensures early operational agility while
            building toward full community ownership &mdash; preventing both
            premature DAO gridlock and unchecked centralisation.
          </p>
        </Section>

        {/* ── Contract Addresses ── */}
        <Section id="contracts" title="Verified Smart Contracts">
          <p>
            All contracts are deployed on{" "}
            <strong>{IS_MAINNET ? "Base mainnet" : "Base Sepolia testnet"}</strong>{" "}
            and verified on Basescan. Click any address to view the source code.
          </p>
          <div className="mt-6 overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-surface-light">
                  <th className="py-3 pr-4 font-semibold text-accent-light">Contract</th>
                  <th className="py-3 font-semibold text-accent-light">Address</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-light text-foreground/80">
                {[
                  { name: "POHToken (ERC-20)", addr: CONTRACTS.token },
                  { name: "POHCharity (Treasury)", addr: CONTRACTS.charity },
                  { name: "POHVesting (Founder Lock)", addr: CONTRACTS.vesting },
                  { name: "POHRewards (Mining)", addr: CONTRACTS.rewards },
                  { name: "POHNodeRegistry", addr: CONTRACTS.registry },
                  { name: "TimelockController", addr: "0x64981B544a20d6933466c363dD175cA1FaD96Bb6" },
                  { name: "POHGovernor", addr: "0x7C96Ed675033F15a53557f1d0190e00B19522e6e" },
                ].map((c) => (
                  <tr key={c.name}>
                    <td className="py-3 pr-4 font-medium text-foreground">{c.name}</td>
                    <td className="py-3">
                      <a
                        href={`${BLOCK_EXPLORER}/address/${c.addr}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="font-mono text-xs text-accent-light underline underline-offset-2 hover:text-accent break-all"
                      >
                        {c.addr}
                      </a>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Section>

        {/* ── Roadmap ── */}
        <Section id="roadmap" title="Roadmap">
          <ol className="relative border-l-2 border-surface-light pl-8">
            <RoadmapPhase
              phase="Phase 1"
              title="Smart Contracts + Testnet"
              status="complete"
            />
            <RoadmapPhase
              phase="Phase 2"
              title="Website + Community"
              status="complete"
            />
            <RoadmapPhase
              phase="Phase 3"
              title="Mainnet Launch on Base"
              status="complete"
            />
            <RoadmapPhase
              phase="Phase 4"
              title="Voyager Block System + BOINC"
              status="active"
            />
            <RoadmapPhase
              phase="Phase 5"
              title="DAO Governance Transition"
            />
            <RoadmapPhase
              phase="Phase 6"
              title="Voyager Chase Fund Activation"
            />
            <RoadmapPhase
              phase="Phase 7"
              title="Voyager 2 Fork"
              last
            />
          </ol>
        </Section>

        {/* ── Legal Disclaimer ── */}
        <Section id="disclaimer" title="Legal Disclaimer">
          <div className="glass-card p-6 text-sm leading-relaxed text-foreground/60">
            POH is a utility token used to participate in charitable giving. It
            is not an investment, and no financial returns are promised. This is
            not financial advice. Consult a licensed attorney before making any
            decisions.
          </div>
        </Section>
      </div>
    </div>
  );
}

/* ──────────────────────────── Sub-components ──────────────────────────── */

function Section({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section id={id} className="mb-16">
      <div className="mb-8 h-px bg-gradient-to-r from-transparent via-accent/20 to-transparent" />
      <h2 className="mb-6 text-2xl font-bold text-accent-light sm:text-3xl">
        {title}
      </h2>
      <div className="space-y-4 text-base leading-relaxed text-foreground/80">
        {children}
      </div>
    </section>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <tr>
      <td className="py-3 pr-4 font-medium text-foreground">{label}</td>
      <td className="py-3 font-mono text-sm">{value}</td>
    </tr>
  );
}

function RoadmapPhase({
  phase,
  title,
  status,
  last,
}: {
  phase: string;
  title: string;
  status?: "complete" | "active";
  last?: boolean;
}) {
  const dotColor =
    status === "complete"
      ? "bg-charity-green"
      : status === "active"
        ? "bg-voyager-gold animate-pulse"
        : "bg-surface-light";

  return (
    <div className={`relative ${last ? "" : "pb-10"}`}>
      {/* Dot on the timeline */}
      <span
        className={`absolute -left-[1.3rem] top-1 h-4 w-4 rounded-full border-2 border-background ${dotColor}`}
      />
      <p className="text-xs font-semibold uppercase tracking-widest text-accent-light">
        {phase}
        {status === "complete" && (
          <span className="ml-2 rounded bg-charity-green/20 px-2 py-0.5 text-[10px] font-bold uppercase text-charity-green">
            Complete
          </span>
        )}
      </p>
      <p className="mt-1 text-base font-medium text-foreground">{title}</p>
    </div>
  );
}
